// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// tpm2
arma::mat tpm2(const arma::mat z, const arma::mat P, const arma::mat Phi);
RcppExport SEXP SpatMCA_tpm2(SEXP zSEXP, SEXP PSEXP, SEXP PhiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type z(zSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type P(PSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Phi(PhiSEXP);
    rcpp_result_gen = Rcpp::wrap(tpm2(z, P, Phi));
    return rcpp_result_gen;
END_RCPP
}
// spatmcacv_rcpp
List spatmcacv_rcpp(NumericMatrix sxr, NumericMatrix syr, NumericMatrix Xr, NumericMatrix Yr, int M, int K, NumericVector tau1ur, NumericVector tau2ur, NumericVector tau1vr, NumericVector tau2vr, NumericVector nkr, int maxit, double tol, NumericVector l2ur, NumericVector l2vr);
RcppExport SEXP SpatMCA_spatmcacv_rcpp(SEXP sxrSEXP, SEXP syrSEXP, SEXP XrSEXP, SEXP YrSEXP, SEXP MSEXP, SEXP KSEXP, SEXP tau1urSEXP, SEXP tau2urSEXP, SEXP tau1vrSEXP, SEXP tau2vrSEXP, SEXP nkrSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP l2urSEXP, SEXP l2vrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type sxr(sxrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type syr(syrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xr(XrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Yr(YrSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau1ur(tau1urSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2ur(tau2urSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau1vr(tau1vrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2vr(tau2vrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nkr(nkrSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type l2ur(l2urSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type l2vr(l2vrSEXP);
    rcpp_result_gen = Rcpp::wrap(spatmcacv_rcpp(sxr, syr, Xr, Yr, M, K, tau1ur, tau2ur, tau1vr, tau2vr, nkr, maxit, tol, l2ur, l2vr));
    return rcpp_result_gen;
END_RCPP
}
// spatmcacvall_rcpp
List spatmcacvall_rcpp(NumericMatrix sxr, NumericMatrix syr, NumericMatrix Xr, NumericMatrix Yr, int M, int K, NumericVector tau1ur, NumericVector tau2ur, NumericVector tau1vr, NumericVector tau2vr, NumericVector nkr, int maxit, double tol, NumericVector l2ur, NumericVector l2vr);
RcppExport SEXP SpatMCA_spatmcacvall_rcpp(SEXP sxrSEXP, SEXP syrSEXP, SEXP XrSEXP, SEXP YrSEXP, SEXP MSEXP, SEXP KSEXP, SEXP tau1urSEXP, SEXP tau2urSEXP, SEXP tau1vrSEXP, SEXP tau2vrSEXP, SEXP nkrSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP l2urSEXP, SEXP l2vrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type sxr(sxrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type syr(syrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xr(XrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Yr(YrSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau1ur(tau1urSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2ur(tau2urSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau1vr(tau1vrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2vr(tau2vrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nkr(nkrSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type l2ur(l2urSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type l2vr(l2vrSEXP);
    rcpp_result_gen = Rcpp::wrap(spatmcacvall_rcpp(sxr, syr, Xr, Yr, M, K, tau1ur, tau2ur, tau1vr, tau2vr, nkr, maxit, tol, l2ur, l2vr));
    return rcpp_result_gen;
END_RCPP
}
