# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tpm2 <- function(z, P, Phi) {
    .Call(`_SpatMCA_tpm2`, z, P, Phi)
}

spatmcacv_rcpp <- function(sxr, syr, Xr, Yr, M, K, tau1ur, tau2ur, tau1vr, tau2vr, nkr, maxit, tol, l2ur, l2vr) {
    .Call(`_SpatMCA_spatmcacv_rcpp`, sxr, syr, Xr, Yr, M, K, tau1ur, tau2ur, tau1vr, tau2vr, nkr, maxit, tol, l2ur, l2vr)
}

spatmcacvall_rcpp <- function(sxr, syr, Xr, Yr, M, K, tau1ur, tau2ur, tau1vr, tau2vr, nkr, maxit, tol, l2ur, l2vr) {
    .Call(`_SpatMCA_spatmcacvall_rcpp`, sxr, syr, Xr, Yr, M, K, tau1ur, tau2ur, tau1vr, tau2vr, nkr, maxit, tol, l2ur, l2vr)
}

